# Version of the compose file format 
version: "3.9"
# Container services
services:
  db:
  #  # image to fetch from docker hub
    image: mongo:3.2.20
    # Mapping of container port to host
    ports:
      - "27017:27017"

  app:
  # Path to Dockerfile 
    build: ./nodeapp/app
    restart: always
    ports:
      - "3000:3000"
    # Environment variables for startup script
    # container will use these variables
    # to start the container with these define variables. 
    environment:
      - DB_HOST=mongodb://db:27017/posts
    depends_on:
      - db
    # links:
    #     - ""